### ISSUE TITLE
token 里的Bearer 去除时，去除不成功

### ISSUE THREAD

**Issue by 1000x** [MQEnergy/gin-framework#1]
token = strings.TrimSpace(strings.TrimLeft(token, "Bearer"))
jwt 返回的token 过长（775字符），上边的代码 去除Bearer时，去除不掉。

**Comment by chenxi2015** [comment]
我这边测试没发现问题，把token贴一下吧
你拉取最新的代码，请求`/token/view`接口测试下。

**Comment by chenxi2015** [comment]
我这边测试没发现问题，把token贴一下吧
你拉取最新的代码，请求`/token/view`接口测试下。
